# Controls the "New Issue" chooser screen.
blank_issues_enabled: false

contact_links:
  - name: Not sure what to do?
    url: https://github.com/orgs/AnaphylactiK-Studios-Inc/discussions
    about: Check Discussions if you're having trouble with anything!
 